/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bot_telegram;

import APITelegram.*;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author marcello
 */
public class JFrameBot extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBot
     */
    Scanner in = new Scanner(System.in);
    String APIToken = "5118962240:AAEEF9fGjOdebIFacVwx3Tnwhtc8Oh5aiug";
    ApiTelegram bot = new ApiTelegram(APIToken);
    ThreadListen listen = new ThreadListen();

    public JFrameBot() throws IOException {
        initComponents();

        bot.getID();

        // Connessione
        connect();
        
        listen.start();
    }

    public void connect() {
        if (bot.exists) {
            lblTitle.setText("Pubblicita_Cattaneo_Bot");
        } else {
            JOptionPane.showMessageDialog(this, "Nessun Bot trovato, modificare APIToken", "Errore", JOptionPane.ERROR_MESSAGE);
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInserisci = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRicerca = new javax.swing.JTextArea();
        btnRicerca = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRisultato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BotPubblicita");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(600, 100));
        setMaximumSize(new java.awt.Dimension(600, 800));
        setMinimumSize(new java.awt.Dimension(600, 800));
        setPreferredSize(new java.awt.Dimension(600, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));

        lblTitle.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        lblTitle.setText("Vuoto");

        lblInserisci.setFont(new java.awt.Font("Liberation Sans", 0, 23)); // NOI18N
        lblInserisci.setText("Inserire citta (/citta nome_citta):");

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N

        txtRicerca.setColumns(20);
        txtRicerca.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        txtRicerca.setRows(5);
        jScrollPane1.setViewportView(txtRicerca);

        btnRicerca.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        btnRicerca.setText("Ricerca");
        btnRicerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRicercaActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);

        txtRisultato.setEditable(false);
        txtRisultato.setColumns(20);
        txtRisultato.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        txtRisultato.setRows(5);
        jScrollPane2.setViewportView(txtRisultato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(lblInserisci)
                            .addComponent(btnRicerca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInserisci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRicerca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRicercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRicercaActionPerformed
        String input = txtRicerca.getText();

        if (input.length() > 5 && "/citta".equals(input.substring(0, 6))) {
            try {
                bot.sendMessage(input.substring(7, input.length()));
            } catch (IOException ex) {
                Logger.getLogger(JFrameBot.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Sintassi comando non corretta", "errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRicercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameBot().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JFrameBot.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRicerca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInserisci;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtRicerca;
    private javax.swing.JTextArea txtRisultato;
    // End of variables declaration//GEN-END:variables
}
